### ISSUE TITLE
The current implementation doesn't work correctly at all

### ISSUE THREAD

**Issue by spodskubka** [Singulink/Singulink.Cryptography.PasswordHasher.Argon2#1]
Hi!

First of all, let me say that I found your PasswordHasher library today and it's just perfect for my use case.
I'm rather surprised that this library is not very popular.
I love the rehash and update functionality, which seems like a textbook implementation of the guidelines on the [OWASP Password Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html).
Also, the documentation provided in the README is understandable, straight to the point, and it explains all available features.

However, I have found a very serious bug in your Argon2 implementation, which unfortunately is not detected by a unit test.

In short, the `Argon2HashAlgorithm.Hash(...)` method always returns a byte array containing only zeroes.
This effectively makes the PasswordHasher believe that all passwords are the same.
The cause for this is that the `SecureArray<byte>.Buffer` is returned directly by the method, but at the same time the `SecureArray<byte>` is disposed through a `using` statement, which in turn zeroes out the buffer before it is actually returned to the caller.

I would suggest two changes:
1. return a copy of the `SecureArray<byte>.Buffer` contents
2. add a unit test which ensures that the `PasswordHasher.Verify(...)` method returns false for the wrong password

If you want I could provide a pull request for that.

**Comment by mikernet** [comment]
Oof, good catch. We were using a different `Argon2` implementation before but changed it over to a signed lib for open-source release and haven't had the opportunity to actually put this version to real use yet, so didn't catch this issue - thanks for the report.

> I'm rather surprised that this library is not very popular.

I'm on a mission to open source all our libs at the moment and haven't had a chance to promote them at all yet, but people have been slowly discovering them. When I get around to making some blog posts and such I'm sure the popularity will pick up :)

Closed via https://github.com/Singulink/Singulink.Cryptography.PasswordHasher.Argon2/commit/c373158d962d132df0ddf587c37179bf887eaed1

**Comment by spodskubka** [comment]
I like your response time, keep up the good work!
